apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
spec:
  project: kafka
  source:
    repoURL: "https://github.com/DonatoVerardi/hello-kafka.git"
    path: "kafka-kustomize"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kafka
  syncPolicy: {}