apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
spec:
  project: jaeger
  source:
    repoURL: "https://github.com/DonatoVerardi/hello-kafka.git"
    path: "jaeger-kustomize"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jaeger
  syncPolicy: {}