apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: grafana
  source:
    repoURL: "https://github.com/DonatoVerardi/hello-kafka.git"
    path: "grafana-kustomize"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy: {}