apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: prometheus
  source:
    repoURL: "https://github.com/DonatoVerardi/hello-kafka.git"
    path: "prometheus-kustomize"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy: {}