apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus
spec:
  # Project description
  description: prometheus

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"